### ISSUE TITLE
Question on the transform function in img.lua

### ISSUE THREAD

**Issue by yxchng** [anewell/pose-hg-train#11]
``` torch
function transform(pt, center, scale, rot, res, invert)
    local pt_ = torch.ones(3)
    pt_[1],pt_[2] = pt[1]-1,pt[2]-1

    local t = getTransform(center, scale, rot, res)
    if invert then
        t = torch.inverse(t)
    end
    local new_point = (t*pt_):sub(1,2):add(1e-4)

    return new_point:int():add(1)
end
```
1. Is there any special reason why do you add 1e-4 to the new_point in the end?
2. Why do you subtract 1 from pt at the start and then add back 1 in the end (instead of just use the original pt)?

**Comment by yxchng** [comment]
in fact, i notice that you do a lot of these kinds of offsetting in your transformation of the image. I don't quite understand the reasoning behind them. Do you mind explaining?

**Comment by anewell** [comment]
It is mostly because Lua is 1-indexed, and that complicates things a little bit. So, for example the coordinate at the top left corner will be (1,1) not (0,0). I had written a lot of this code originally in Python and when I was converting it over I wanted to make sure it had the same behavior, so the easiest thing to do was just to subtract and add 1 before and after applying the transformation.

As for the 1e-4, well, to tell the truth I remember it coming up at some point when I had to debug some funny behavior from the transformations, but now I can't remember why it is still there, it doesn't really seem necessary. (I realize that is not the best answer I will definitely look into it see if it still needs to be there)

**Comment by yxchng** [comment]
```torch   
   local new_ = {1,-1,math.max(1, -ul[2] + 2), math.min(br[2], ht+1) - ul[2],
                       math.max(1, -ul[1] + 2), math.min(br[1], wd+1) - ul[1]}
    local old_ = {1,-1,math.max(1, ul[2]), math.min(br[2], ht+1) - 1,
                       math.max(1, ul[1]), math.min(br[1], wd+1) - 1}
```

Sorry for bothering you again. I am not understanding why you need to check for max(1, -ul + 2). The condition seem to suggest that the result is not 1 only when ul is negative, but can ul be negative? What does it mean when ul is negative?

**Comment by yxchng** [comment]
Can I know what is the output of your getTransform function? I cannot relate it to why there can be negative ul in the following statement. 

``` torch
    local new_ = {1,-1,math.max(1, -ul[2] + 2), math.min(br[2], ht+1) - ul[2],
                       math.max(1, -ul[1] + 2), math.min(br[1], wd+1) - ul[1]}
    local old_ = {1,-1,math.max(1, ul[2]), math.min(br[2], ht+1) - 1,
                       math.max(1, ul[1]), math.min(br[1], wd+1) - 1}
```

and if ul is negative, seems like new_and old_ would not match
