### ISSUE TITLE
Error running with "-continue"

### ISSUE THREAD

**Issue by wxy1224** [anewell/pose-hg-train#13]
Hi anewell, thanks for sharing this project!
I was running the command `th main.lua -expID test-run` successfully, and I had to stop after epoch 1. Then I wanted to resume it by the command `th main.lua -expID test-run -continue` but I met the error below.

```
Saving everything to: /home/ubuntu/pose-hg-train/exp/mpii/test-run  
/home/ubuntu/torch/install/bin/luajit: /home/ubuntu/pose-hg-train/src/opts.lua:111: attempt to perform arithmetic on field 'lastEpoch' (a nil value)
stack traceback:
    /home/ubuntu/pose-hg-train/src/opts.lua:111: in main chunk
    [C]: in function 'dofile'
    /home/ubuntu/pose-hg-train/src/ref.lua:17: in main chunk
    [C]: in function 'dofile'
    main.lua:2: in main chunk
    [C]: in function 'dofile'
    ...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670
```

Is that the lastEpoch is not saved correctly? Have you seen similar errors before and any idea how to solve this? 
Thank you in advance.

**Comment by yxchng** [comment]
@wxy1224 did you finish running the entire experiment successfully or just epoch 1? I am facing error half way through:

==> Starting epoch: 29/100
 [==================== 8000/8000 ==============>]  Tot: 42m50s | Step: 322ms
      train : Loss: 0.0060905 Acc: 0.7886
 [==================== 1000/1000 ==============>]  Tot: 1m16s | Step: 75ms
      valid : Loss: 0.0061668 Acc: 0.7814
==> Starting epoch: 30/100
 [==================== 8000/8000 ==============>]  Tot: 42m54s | Step: 324ms
      train : Loss: 0.0060351 Acc: 0.7905
 [==================== 1000/1000 ==============>]  Tot: 1m16s | Step: 76ms
      valid : Loss: 0.0063810 Acc: 0.7750
==> Starting epoch: 31/100
 [==================== 8000/8000 ==============>]  Tot: 43m12s | Step: 328ms
      train : Loss: 0.0059887 Acc: 0.7935
 [==================== 1000/1000 ==============>]  Tot: 1m15s | Step: 74ms
      valid : Loss: 0.0061673 Acc: 0.7800
==> Starting epoch: 32/100
THCudaCheck FAIL file=/home/yx/torch/extra/cutorch/lib/THC/generic/THCStorage.c line=147 error=4 : unspecified launch failure
/home/yx/torch/install/bin/luajit: cuda runtime error (4) : unspecified launch failure at /home/yx/torch/extra/cutorch/lib/THC/generic/THCStorage.c:147

**Comment by anewell** [comment]
The way the code is written, to continue an experiment it needs to save an intermediate snapshot, by default this is done every 5 rounds (set by the '-snapshot' option). In your case, after the first epoch the code will not have saved a model or updated the options with a 'lastEpoch' value.

There's another detail, by default the code will look to continue training from the 'final_model.t7' file, if an experiment runs to completion this is saved properly, but otherwise intermediate snapshots are saved in the form 'model_X.t7'. If the experiment crashed for whatever reason, you can take the most recent model, for example 'model_30.t7' move it to 'final_model.t7' and then the '-continue' option will work.

As for yxchng's comment, I have not seen that error before, sorry, not sure what would cause it.
