### ISSUE TITLE
Difference between *.h5 annotations and official .mat annotation

### ISSUE THREAD

**Issue by omair-kg** [anewell/pose-hg-train#32]
Hi i noticed that for some of the images there is a difference between the annotations in the h5 files and the official mpii_human_pose_v1_u12_1.mat file. 

For the first entry for example, the order of the parts is different (not really that big of a deal) and the value for scale (3.7763 vs 3.02) and center (594,257 vs 594,302) are different. I made sure that both refer to the same image and the same person id within the image. 
Is there any particular reason for this? Does it make a difference if i use one or the other?

**Comment by anewell** [comment]
Sorry for the confusion, the files in the annot/ folder (train.h5, valid.h5, and test.h5) are old and not used anymore. I forgot to remove them when updating the repository. The annotation file used by the code is simply data/mpii/annot.h5, and you should find that the center/scale terms match up with the official .mat file.

The adjustment to the scale and center terms was a slight modification so that the code would produce better crops around figures. This is now done directly in the code here: https://github.com/anewell/pose-hg-train/blob/master/src/util/dataset/mpii.lua#L92

**Comment by omair-kg** [comment]
Thank you for the explanation. Final question regarding this point, how do i make sure then that the validation images are the same as yours? The code in its current form selects the validation images at random.

**Comment by anewell** [comment]
There's a command line option for it: https://github.com/anewell/pose-hg-train/blob/master/src/util/dataset/mpii.lua#L34

**Comment by omair-kg** [comment]
Thanks.
