### ISSUE TITLE
The amplitude of predicted maps

### ISSUE THREAD

**Issue by hzh8311** [anewell/pose-hg-train#40]
since only `relu` used in the network, how to ensure that the the amplitude of predicted maps is [0-1] just same as the gaussian maps?

**Comment by anewell** [comment]
Nothing guarantees that the output will be between 0 and 1. While the network will learn to match the output of the gaussian maps as closely as possible due to the loss penalty, it is possible it may output negative values for example. But that is not a problem, all we care about are local maxima in the output heatmap.
